/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CanisterDetails {
  'status' : CanisterStatus,
  'controllers' : Array<Principal>,
  'cycleBalance' : Cycles,
  'createdAt' : Timestamp,
  'customName' : string,
  'lastChecked' : Timestamp,
  'canisterId' : CanisterId,
}
export type CanisterId = Principal;
export type CanisterStatus = { 'stopped' : null } |
  { 'stopping' : null } |
  { 'running' : null };
export interface CanisterSummary {
  'status' : CanisterStatus,
  'cycleBalance' : Cycles,
  'customName' : string,
  'lastChecked' : Timestamp,
  'canisterId' : CanisterId,
}
export type Cycles = bigint;
export type E8s = bigint;
export interface Page {
  'total' : bigint,
  'page' : bigint,
  'pageSize' : bigint,
  'items' : Array<CanisterSummary>,
}
export interface Page_1 {
  'total' : bigint,
  'page' : bigint,
  'pageSize' : bigint,
  'items' : Array<Transaction>,
}
export type Result = { 'ok' : bigint } |
  { 'err' : string };
export type Result_1 = { 'ok' : Cycles } |
  { 'err' : string };
export type Result_2 = { 'ok' : null } |
  { 'err' : string };
export type Timestamp = bigint;
export interface Transaction {
  'id' : bigint,
  'userId' : UserId,
  'kind' : TxKind,
  'memo' : string,
  'timestamp' : Timestamp,
  'amountE8s' : E8s,
}
export type TxKind = {
    'topUp' : { 'cyclesAdded' : Cycles, 'canisterId' : Principal }
  } |
  { 'icpTransfer' : { 'toAccountId' : string } };
export interface UserAccount {
  'accountId' : string,
  'userId' : UserId,
  'subaccount' : Uint8Array,
}
export type UserId = Principal;
export interface _SERVICE {
  'addCanister' : ActorMethod<[CanisterId, string], Result_2>,
  'addController' : ActorMethod<[CanisterId, Principal], Result_2>,
  'getAppPrincipal' : ActorMethod<[], Principal>,
  'getCanisterDetails' : ActorMethod<[CanisterId], [] | [CanisterDetails]>,
  'getMyAccount' : ActorMethod<[], UserAccount>,
  'getMyBalance' : ActorMethod<[], E8s>,
  'getTransactionHistory' : ActorMethod<[bigint], Page_1>,
  'listCanisters' : ActorMethod<[bigint], Page>,
  'removeCanister' : ActorMethod<[CanisterId], Result_2>,
  'removeController' : ActorMethod<[CanisterId, Principal], Result_2>,
  'renameCanister' : ActorMethod<[CanisterId, string], Result_2>,
  'topUpCanister' : ActorMethod<[CanisterId, E8s], Result_1>,
  'transferIcp' : ActorMethod<[string, E8s, string], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];