/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CanisterId = IDL.Principal;
export const Result_2 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const E8s = IDL.Nat64;
export const Cycles = IDL.Nat;
export const CreateCanisterResult = IDL.Record({
  'cyclesSeeded' : Cycles,
  'canisterId' : CanisterId,
});
export const Result_3 = IDL.Variant({
  'ok' : CreateCanisterResult,
  'err' : IDL.Text,
});
export const CanisterStatus = IDL.Variant({
  'stopped' : IDL.Null,
  'stopping' : IDL.Null,
  'running' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const CanisterDetails = IDL.Record({
  'status' : CanisterStatus,
  'controllers' : IDL.Vec(IDL.Principal),
  'cycleBalance' : Cycles,
  'createdAt' : Timestamp,
  'customName' : IDL.Text,
  'lastChecked' : Timestamp,
  'fetchFailed' : IDL.Bool,
  'canisterId' : CanisterId,
});
export const CreationCostEstimate = IDL.Record({
  'creationFeeIcpE8s' : E8s,
  'creationCycles' : Cycles,
  'cyclesPerIcp' : IDL.Nat,
  'estimatedSeedCycles' : Cycles,
  'transferFeeE8s' : E8s,
  'seedCyclesIcpE8s' : E8s,
  'totalIcpRequiredE8s' : E8s,
});
export const DashboardItem = IDL.Record({
  'cycleBalance' : Cycles,
  'customName' : IDL.Text,
  'isController' : IDL.Bool,
  'lastInteractedAt' : Timestamp,
  'canisterId' : CanisterId,
});
export const UserId = IDL.Principal;
export const UserAccount = IDL.Record({
  'accountId' : IDL.Text,
  'userId' : UserId,
  'subaccount' : IDL.Vec(IDL.Nat8),
});
export const TxKind = IDL.Variant({
  'topUp' : IDL.Record({
    'cyclesAdded' : Cycles,
    'canisterId' : IDL.Principal,
  }),
  'icpTransfer' : IDL.Record({ 'toAccountId' : IDL.Text }),
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'userId' : UserId,
  'kind' : TxKind,
  'memo' : IDL.Text,
  'timestamp' : Timestamp,
  'amountE8s' : E8s,
});
export const Page_1 = IDL.Record({
  'total' : IDL.Nat,
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'items' : IDL.Vec(Transaction),
});
export const CanisterSummary = IDL.Record({
  'status' : CanisterStatus,
  'cycleBalance' : Cycles,
  'customName' : IDL.Text,
  'lastChecked' : Timestamp,
  'isController' : IDL.Bool,
  'fetchFailed' : IDL.Bool,
  'canisterId' : CanisterId,
});
export const Page = IDL.Record({
  'total' : IDL.Nat,
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'items' : IDL.Vec(CanisterSummary),
});
export const CanisterInfo = IDL.Record({
  'cachedCycleBalance' : Cycles,
  'addedAt' : Timestamp,
  'customName' : IDL.Text,
  'isController' : IDL.Bool,
  'lastInteractedAt' : Timestamp,
  'canisterId' : CanisterId,
});
export const Result_1 = IDL.Variant({ 'ok' : Cycles, 'err' : IDL.Text });
export const Result = IDL.Variant({ 'ok' : IDL.Nat64, 'err' : IDL.Text });

export const idlService = IDL.Service({
  'addCanister' : IDL.Func([CanisterId, IDL.Text], [Result_2], []),
  'addController' : IDL.Func([CanisterId, IDL.Principal], [Result_2], []),
  'createCanister' : IDL.Func([IDL.Text, E8s], [Result_3], []),
  'getAppPrincipal' : IDL.Func([], [IDL.Principal], ['query']),
  'getCanisterDetails' : IDL.Func([CanisterId], [IDL.Opt(CanisterDetails)], []),
  'getCreationCostEstimate' : IDL.Func([E8s], [CreationCostEstimate], []),
  'getIcpXdrConversionRate' : IDL.Func([], [IDL.Nat], []),
  'getLowestCyclesCanisters' : IDL.Func([], [IDL.Vec(DashboardItem)], []),
  'getMyAccount' : IDL.Func([], [UserAccount], []),
  'getMyBalance' : IDL.Func([], [E8s], []),
  'getRecentCanisters' : IDL.Func([], [IDL.Vec(DashboardItem)], []),
  'getTransactionHistory' : IDL.Func([IDL.Nat], [Page_1], []),
  'listCanisters' : IDL.Func([IDL.Nat], [Page], []),
  'removeCanister' : IDL.Func([CanisterId], [Result_2], []),
  'removeController' : IDL.Func([CanisterId, IDL.Principal], [Result_2], []),
  'renameCanister' : IDL.Func([CanisterId, IDL.Text], [Result_2], []),
  'searchCanisters' : IDL.Func([IDL.Text], [IDL.Vec(CanisterInfo)], ['query']),
  'topUpCanister' : IDL.Func([CanisterId, E8s], [Result_1], []),
  'transferIcp' : IDL.Func([IDL.Text, E8s, IDL.Text], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CanisterId = IDL.Principal;
  const Result_2 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const E8s = IDL.Nat64;
  const Cycles = IDL.Nat;
  const CreateCanisterResult = IDL.Record({
    'cyclesSeeded' : Cycles,
    'canisterId' : CanisterId,
  });
  const Result_3 = IDL.Variant({
    'ok' : CreateCanisterResult,
    'err' : IDL.Text,
  });
  const CanisterStatus = IDL.Variant({
    'stopped' : IDL.Null,
    'stopping' : IDL.Null,
    'running' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const CanisterDetails = IDL.Record({
    'status' : CanisterStatus,
    'controllers' : IDL.Vec(IDL.Principal),
    'cycleBalance' : Cycles,
    'createdAt' : Timestamp,
    'customName' : IDL.Text,
    'lastChecked' : Timestamp,
    'fetchFailed' : IDL.Bool,
    'canisterId' : CanisterId,
  });
  const CreationCostEstimate = IDL.Record({
    'creationFeeIcpE8s' : E8s,
    'creationCycles' : Cycles,
    'cyclesPerIcp' : IDL.Nat,
    'estimatedSeedCycles' : Cycles,
    'transferFeeE8s' : E8s,
    'seedCyclesIcpE8s' : E8s,
    'totalIcpRequiredE8s' : E8s,
  });
  const DashboardItem = IDL.Record({
    'cycleBalance' : Cycles,
    'customName' : IDL.Text,
    'isController' : IDL.Bool,
    'lastInteractedAt' : Timestamp,
    'canisterId' : CanisterId,
  });
  const UserId = IDL.Principal;
  const UserAccount = IDL.Record({
    'accountId' : IDL.Text,
    'userId' : UserId,
    'subaccount' : IDL.Vec(IDL.Nat8),
  });
  const TxKind = IDL.Variant({
    'topUp' : IDL.Record({
      'cyclesAdded' : Cycles,
      'canisterId' : IDL.Principal,
    }),
    'icpTransfer' : IDL.Record({ 'toAccountId' : IDL.Text }),
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'userId' : UserId,
    'kind' : TxKind,
    'memo' : IDL.Text,
    'timestamp' : Timestamp,
    'amountE8s' : E8s,
  });
  const Page_1 = IDL.Record({
    'total' : IDL.Nat,
    'page' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'items' : IDL.Vec(Transaction),
  });
  const CanisterSummary = IDL.Record({
    'status' : CanisterStatus,
    'cycleBalance' : Cycles,
    'customName' : IDL.Text,
    'lastChecked' : Timestamp,
    'isController' : IDL.Bool,
    'fetchFailed' : IDL.Bool,
    'canisterId' : CanisterId,
  });
  const Page = IDL.Record({
    'total' : IDL.Nat,
    'page' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'items' : IDL.Vec(CanisterSummary),
  });
  const CanisterInfo = IDL.Record({
    'cachedCycleBalance' : Cycles,
    'addedAt' : Timestamp,
    'customName' : IDL.Text,
    'isController' : IDL.Bool,
    'lastInteractedAt' : Timestamp,
    'canisterId' : CanisterId,
  });
  const Result_1 = IDL.Variant({ 'ok' : Cycles, 'err' : IDL.Text });
  const Result = IDL.Variant({ 'ok' : IDL.Nat64, 'err' : IDL.Text });
  
  return IDL.Service({
    'addCanister' : IDL.Func([CanisterId, IDL.Text], [Result_2], []),
    'addController' : IDL.Func([CanisterId, IDL.Principal], [Result_2], []),
    'createCanister' : IDL.Func([IDL.Text, E8s], [Result_3], []),
    'getAppPrincipal' : IDL.Func([], [IDL.Principal], ['query']),
    'getCanisterDetails' : IDL.Func(
        [CanisterId],
        [IDL.Opt(CanisterDetails)],
        [],
      ),
    'getCreationCostEstimate' : IDL.Func([E8s], [CreationCostEstimate], []),
    'getIcpXdrConversionRate' : IDL.Func([], [IDL.Nat], []),
    'getLowestCyclesCanisters' : IDL.Func([], [IDL.Vec(DashboardItem)], []),
    'getMyAccount' : IDL.Func([], [UserAccount], []),
    'getMyBalance' : IDL.Func([], [E8s], []),
    'getRecentCanisters' : IDL.Func([], [IDL.Vec(DashboardItem)], []),
    'getTransactionHistory' : IDL.Func([IDL.Nat], [Page_1], []),
    'listCanisters' : IDL.Func([IDL.Nat], [Page], []),
    'removeCanister' : IDL.Func([CanisterId], [Result_2], []),
    'removeController' : IDL.Func([CanisterId, IDL.Principal], [Result_2], []),
    'renameCanister' : IDL.Func([CanisterId, IDL.Text], [Result_2], []),
    'searchCanisters' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CanisterInfo)],
        ['query'],
      ),
    'topUpCanister' : IDL.Func([CanisterId, E8s], [Result_1], []),
    'transferIcp' : IDL.Func([IDL.Text, E8s, IDL.Text], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };