/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CanisterInfo {
    cachedCycleBalance: Cycles;
    addedAt: Timestamp;
    customName: string;
    isController: boolean;
    lastInteractedAt: Timestamp;
    canisterId: CanisterId;
}
export type Timestamp = bigint;
export type Result_2 = {
    __kind__: "ok";
    ok: Cycles;
} | {
    __kind__: "err";
    err: string;
};
export interface CanisterDetails {
    status: CanisterStatus;
    controllers: Array<Principal>;
    cycleBalance: Cycles;
    createdAt: Timestamp;
    customName: string;
    lastChecked: Timestamp;
    fetchFailed: boolean;
    canisterId: CanisterId;
}
export interface UserAccount {
    accountId: string;
    userId: UserId;
    subaccount: Uint8Array;
}
export type TxKind = {
    __kind__: "topUp";
    topUp: {
        cyclesAdded: Cycles;
        canisterId: Principal;
    };
} | {
    __kind__: "icpTransfer";
    icpTransfer: {
        toAccountId: string;
    };
};
export interface Page_1 {
    total: bigint;
    page: bigint;
    pageSize: bigint;
    items: Array<Transaction>;
}
export type Result_1 = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
};
export interface CreateCanisterResult {
    cyclesSeeded: Cycles;
    canisterId: CanisterId;
}
export interface Transaction {
    id: bigint;
    userId: UserId;
    kind: TxKind;
    memo: string;
    timestamp: Timestamp;
    amountE8s: E8s;
}
export type Result_4 = {
    __kind__: "ok";
    ok: CreateCanisterResult;
} | {
    __kind__: "err";
    err: string;
};
export type UserId = Principal;
export interface DashboardItem {
    cycleBalance: Cycles;
    customName: string;
    isController: boolean;
    lastInteractedAt: Timestamp;
    canisterId: CanisterId;
}
export type Result = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
};
export type Result_3 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export interface Page {
    total: bigint;
    page: bigint;
    pageSize: bigint;
    items: Array<CanisterSummary>;
}
export type E8s = bigint;
export type Cycles = bigint;
export interface CreationCostEstimate {
    creationFeeIcpE8s: E8s;
    creationCycles: Cycles;
    cyclesPerIcp: bigint;
    estimatedSeedCycles: Cycles;
    transferFeeE8s: E8s;
    seedCyclesIcpE8s: E8s;
    totalIcpRequiredE8s: E8s;
}
export interface CanisterSummary {
    status: CanisterStatus;
    cycleBalance: Cycles;
    customName: string;
    lastChecked: Timestamp;
    isController: boolean;
    fetchFailed: boolean;
    canisterId: CanisterId;
}
export type CanisterId = Principal;
export enum CanisterStatus {
    stopped = "stopped",
    stopping = "stopping",
    running = "running"
}
export interface backendInterface {
    addCanister(canisterId: CanisterId, customName: string): Promise<Result_3>;
    addController(canisterId: CanisterId, controller: Principal): Promise<Result_3>;
    createCanister(name: string, seedCyclesIcpE8s: E8s): Promise<Result_4>;
    getAppPrincipal(): Promise<Principal>;
    getCanisterDetails(canisterId: CanisterId): Promise<CanisterDetails | null>;
    getCreationCostEstimate(seedCyclesIcpE8s: E8s): Promise<CreationCostEstimate>;
    getIcpXdrConversionRate(): Promise<bigint>;
    getLowestCyclesCanisters(): Promise<Array<DashboardItem>>;
    getMyAccount(): Promise<UserAccount>;
    getMyBalance(): Promise<E8s>;
    getRecentCanisters(): Promise<Array<DashboardItem>>;
    getTransactionHistory(page: bigint): Promise<Page_1>;
    listCanisters(page: bigint): Promise<Page>;
    removeCanister(canisterId: CanisterId): Promise<Result_3>;
    removeController(canisterId: CanisterId, controller: Principal): Promise<Result_3>;
    renameCanister(canisterId: CanisterId, newName: string): Promise<Result_3>;
    searchCanisters(queryText: string): Promise<Array<CanisterInfo>>;
    topUpCanister(canisterId: CanisterId, icpAmountE8s: E8s): Promise<Result_2>;
    transferCycles(fromCanisterId: Principal, toCanisterId: Principal, amount: bigint): Promise<Result_1>;
    transferIcp(toAccountId: string, amountE8s: E8s, memo: string): Promise<Result>;
    withdrawCyclesTo(destination: Principal, amount: bigint): Promise<void>;
}
import type { CanisterDetails as _CanisterDetails, CanisterId as _CanisterId, CanisterStatus as _CanisterStatus, CanisterSummary as _CanisterSummary, CreateCanisterResult as _CreateCanisterResult, Cycles as _Cycles, E8s as _E8s, Page as _Page, Page_1 as _Page_1, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Result_3 as _Result_3, Result_4 as _Result_4, Timestamp as _Timestamp, Transaction as _Transaction, TxKind as _TxKind, UserId as _UserId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCanister(arg0: CanisterId, arg1: string): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.addCanister(arg0, arg1);
                return from_candid_Result_3_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCanister(arg0, arg1);
            return from_candid_Result_3_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addController(arg0: CanisterId, arg1: Principal): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.addController(arg0, arg1);
                return from_candid_Result_3_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addController(arg0, arg1);
            return from_candid_Result_3_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCanister(arg0: string, arg1: E8s): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.createCanister(arg0, arg1);
                return from_candid_Result_4_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCanister(arg0, arg1);
            return from_candid_Result_4_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAppPrincipal(): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppPrincipal();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppPrincipal();
            return result;
        }
    }
    async getCanisterDetails(arg0: CanisterId): Promise<CanisterDetails | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCanisterDetails(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCanisterDetails(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCreationCostEstimate(arg0: E8s): Promise<CreationCostEstimate> {
        if (this.processError) {
            try {
                const result = await this.actor.getCreationCostEstimate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCreationCostEstimate(arg0);
            return result;
        }
    }
    async getIcpXdrConversionRate(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getIcpXdrConversionRate();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIcpXdrConversionRate();
            return result;
        }
    }
    async getLowestCyclesCanisters(): Promise<Array<DashboardItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLowestCyclesCanisters();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLowestCyclesCanisters();
            return result;
        }
    }
    async getMyAccount(): Promise<UserAccount> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyAccount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyAccount();
            return result;
        }
    }
    async getMyBalance(): Promise<E8s> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBalance();
            return result;
        }
    }
    async getRecentCanisters(): Promise<Array<DashboardItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentCanisters();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentCanisters();
            return result;
        }
    }
    async getTransactionHistory(arg0: bigint): Promise<Page_1> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionHistory(arg0);
                return from_candid_Page_1_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionHistory(arg0);
            return from_candid_Page_1_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async listCanisters(arg0: bigint): Promise<Page> {
        if (this.processError) {
            try {
                const result = await this.actor.listCanisters(arg0);
                return from_candid_Page_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCanisters(arg0);
            return from_candid_Page_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeCanister(arg0: CanisterId): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.removeCanister(arg0);
                return from_candid_Result_3_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeCanister(arg0);
            return from_candid_Result_3_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeController(arg0: CanisterId, arg1: Principal): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.removeController(arg0, arg1);
                return from_candid_Result_3_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeController(arg0, arg1);
            return from_candid_Result_3_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async renameCanister(arg0: CanisterId, arg1: string): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.renameCanister(arg0, arg1);
                return from_candid_Result_3_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.renameCanister(arg0, arg1);
            return from_candid_Result_3_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchCanisters(arg0: string): Promise<Array<CanisterInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchCanisters(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchCanisters(arg0);
            return result;
        }
    }
    async topUpCanister(arg0: CanisterId, arg1: E8s): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.topUpCanister(arg0, arg1);
                return from_candid_Result_2_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.topUpCanister(arg0, arg1);
            return from_candid_Result_2_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async transferCycles(arg0: Principal, arg1: Principal, arg2: bigint): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.transferCycles(arg0, arg1, arg2);
                return from_candid_Result_1_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transferCycles(arg0, arg1, arg2);
            return from_candid_Result_1_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async transferIcp(arg0: string, arg1: E8s, arg2: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.transferIcp(arg0, arg1, arg2);
                return from_candid_Result_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transferIcp(arg0, arg1, arg2);
            return from_candid_Result_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async withdrawCyclesTo(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.withdrawCyclesTo(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.withdrawCyclesTo(arg0, arg1);
            return result;
        }
    }
}
function from_candid_CanisterDetails_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CanisterDetails): CanisterDetails {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_CanisterStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CanisterStatus): CanisterStatus {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_CanisterSummary_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CanisterSummary): CanisterSummary {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Page_1_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Page_1): Page_1 {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Page_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Page): Page {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Result_3_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_3): Result_3 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_4_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_4): Result_4 {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_TxKind_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TxKind): TxKind {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CanisterDetails]): CanisterDetails | null {
    return value.length === 0 ? null : from_candid_CanisterDetails_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    page: bigint;
    pageSize: bigint;
    items: Array<_Transaction>;
}): {
    total: bigint;
    page: bigint;
    pageSize: bigint;
    items: Array<Transaction>;
} {
    return {
        total: value.total,
        page: value.page,
        pageSize: value.pageSize,
        items: from_candid_vec_n12(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    userId: _UserId;
    kind: _TxKind;
    memo: string;
    timestamp: _Timestamp;
    amountE8s: _E8s;
}): {
    id: bigint;
    userId: UserId;
    kind: TxKind;
    memo: string;
    timestamp: Timestamp;
    amountE8s: E8s;
} {
    return {
        id: value.id,
        userId: value.userId,
        kind: from_candid_TxKind_n15(_uploadFile, _downloadFile, value.kind),
        memo: value.memo,
        timestamp: value.timestamp,
        amountE8s: value.amountE8s
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    page: bigint;
    pageSize: bigint;
    items: Array<_CanisterSummary>;
}): {
    total: bigint;
    page: bigint;
    pageSize: bigint;
    items: Array<CanisterSummary>;
} {
    return {
        total: value.total,
        page: value.page,
        pageSize: value.pageSize,
        items: from_candid_vec_n19(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _CanisterStatus;
    cycleBalance: _Cycles;
    customName: string;
    lastChecked: _Timestamp;
    isController: boolean;
    fetchFailed: boolean;
    canisterId: _CanisterId;
}): {
    status: CanisterStatus;
    cycleBalance: Cycles;
    customName: string;
    lastChecked: Timestamp;
    isController: boolean;
    fetchFailed: boolean;
    canisterId: CanisterId;
} {
    return {
        status: from_candid_CanisterStatus_n8(_uploadFile, _downloadFile, value.status),
        cycleBalance: value.cycleBalance,
        customName: value.customName,
        lastChecked: value.lastChecked,
        isController: value.isController,
        fetchFailed: value.fetchFailed,
        canisterId: value.canisterId
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _CanisterStatus;
    controllers: Array<Principal>;
    cycleBalance: _Cycles;
    createdAt: _Timestamp;
    customName: string;
    lastChecked: _Timestamp;
    fetchFailed: boolean;
    canisterId: _CanisterId;
}): {
    status: CanisterStatus;
    controllers: Array<Principal>;
    cycleBalance: Cycles;
    createdAt: Timestamp;
    customName: string;
    lastChecked: Timestamp;
    fetchFailed: boolean;
    canisterId: CanisterId;
} {
    return {
        status: from_candid_CanisterStatus_n8(_uploadFile, _downloadFile, value.status),
        controllers: value.controllers,
        cycleBalance: value.cycleBalance,
        createdAt: value.createdAt,
        customName: value.customName,
        lastChecked: value.lastChecked,
        fetchFailed: value.fetchFailed,
        canisterId: value.canisterId
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    topUp: {
        cyclesAdded: _Cycles;
        canisterId: Principal;
    };
} | {
    icpTransfer: {
        toAccountId: string;
    };
}): {
    __kind__: "topUp";
    topUp: {
        cyclesAdded: Cycles;
        canisterId: Principal;
    };
} | {
    __kind__: "icpTransfer";
    icpTransfer: {
        toAccountId: string;
    };
} {
    return "topUp" in value ? {
        __kind__: "topUp",
        topUp: value.topUp
    } : "icpTransfer" in value ? {
        __kind__: "icpTransfer",
        icpTransfer: value.icpTransfer
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Cycles;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Cycles;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _CreateCanisterResult;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: CreateCanisterResult;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stopped: null;
} | {
    stopping: null;
} | {
    running: null;
}): CanisterStatus {
    return "stopped" in value ? CanisterStatus.stopped : "stopping" in value ? CanisterStatus.stopping : "running" in value ? CanisterStatus.running : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CanisterSummary>): Array<CanisterSummary> {
    return value.map((x)=>from_candid_CanisterSummary_n20(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
